export default {
    instruction: [
        "RECURSOS VIRTUALES PARA DOS FLUJOS:",
        "Este prompt se usa en el flujo A (texto). El flujo B generará imágenes/diagramas y resolverá enlaces externos.",
        "",
        "1) IMÁGENES GENERADAS POR IA (resources.images):",
        "- Genera entre 2 y 4 imágenes ilustradas si el tema lo amerita.",
        "- Cada imagen debe incluir: id, title, prompt, moment.",
        "- El 'moment' debe ser exactamente uno de: 'Inicio', 'Desarrollo', 'Cierre'.",
        "- El 'prompt' debe ser detallado y apto para un modelo de imagen IA.",
        "- Incluye explícitamente: 'Text inside the image must be in Spanish'.",
        "",
        "2) SINCRONIZACIÓN CON TEXTO:",
        "- Cuando una estrategia mencione usar una imagen generada, inserta {{imagen:Título Exacto}}.",
        "- El título debe coincidir EXACTAMENTE con resources.images[].title.",
        "",
        "3) ORGANIZADOR MERMAID (resources.organizer):",
        "- Incluye id, title, type y mermaidCode.",
        "- Usa 'graph TD' o 'mindmap' en la PRIMERA línea.",
        "- Los nodos deben usar comillas dobles en los textos.",
        "",
        "════════════════════════════════════════════════════════════",
        "4) MATERIALES POR SECCIÓN - ¡MUY IMPORTANTE!",
        "════════════════════════════════════════════════════════════",
        "En inicio.materiales, desarrollo.materiales, cierre.materiales, tareaCasa.materiales",
        "DEBES incluir ítems con estos PREFIJOS EXACTOS cuando corresponda:",
        "",
        "👉 IMG_GEN: <Título Exacto>",
        "   Referencia a una imagen IA que debe existir en resources.images.",
        "",
        "👉 VID_YT: <Título descriptivo> :: SEARCH: <consulta de búsqueda>",
        "   Para videos de YouTube. El sistema buscará el video real.",
        "   Ejemplo: VID_YT: Canción de las Vocales :: SEARCH: cancion infantil vocales español",
        "",
        "👉 IMG_URL: <Título descriptivo> :: SEARCH: <consulta de búsqueda>",
        "   Para FOTOS REALES (no ilustraciones). El sistema buscará la imagen.",
        "   Ejemplo: IMG_URL: Foto de Elefante Real :: SEARCH: elefante africano foto real",
        "",
        "👉 DIAG_PROMPT: <Título> :: <instrucción breve>",
        "   Para solicitar un diagrama adicional por sección.",
        "",
        "⚠️ NUNCA inventes URLs. Usa siempre el formato SEARCH: para que el sistema busque.",
        "⚠️ Si el docente pide videos o fotos reales, DEBES usar VID_YT o IMG_URL con SEARCH."
    ].join("\n")
};

